using System.Collections.Generic;
using System.IO;
using System.Linq;

using Rbx2Source.Assembler;

namespace Rbx2Source.StudioMdl
{
    /// <summary>
    /// Implementation for writing Source's StudioMdl Data format.
    /// See: https://developer.valvesoftware.com/wiki/Studiomdl_Data
    /// </summary>

    public class StudioMdlWriter
    {
        private StringWriter buffer;

        public List<Node> Nodes;
        public List<Triangle> Triangles;
        public List<BoneKeyframe> Skeleton;
        public Dictionary<string, Material> Materials;

        private void writeEntities<T>(List<T> entities) where T : IStudioMdlEntity<T>
        {
            if (entities.Count > 0)
            {
                var groupName = entities[0].GroupName;
                buffer.WriteLine('\n' + groupName);

                foreach (T entity in entities)
                    entity.WriteStudioMdl(buffer, entity, entities);

                buffer.WriteLine("end");
            }
        }

        public string BuildFile(bool writeGeometry = true)
        {
            buffer = new StringWriter();

            buffer.WriteLine("// Generated by CloneTrooper1019's Rbx2Source tool!");
            buffer.WriteLine("// Please do not edit this file while the program is running.");
            buffer.WriteLine("// The file was set to read-only for a reason ;)\n");
            buffer.WriteLine("version 1");

            writeEntities(Nodes);
            writeEntities(Skeleton);

            if (writeGeometry)
                writeEntities(Triangles);

            return buffer.ToString();
        }

        public StudioMdlWriter()
        {
            Nodes     = new List<Node>();
            Triangles = new List<Triangle>();
            Skeleton  = new List<BoneKeyframe>();

            Materials = new Dictionary<string, Material>();
        }
    }
}
